export enum DocLabelCmBluTypes {
  'ADMINISTRATIVO-1' = 'ADMINISTRATIVO',
  'LEGISLATIVO-2' = 'LEGISLATIVO',
  'LEIS_MUNICIPAIS-3' = 'LEIS MUNICIPAIS',
  'PROJETOS-2' = 'PROJETOS',
  'PROPOSICOES-2' = 'PROPOSIÇÕES',
}
