export enum DocLabelCmBluSubTypes {
  'DECRETO-LEGISLATIVO-203' = 'DECRETO LEGISLATIVO',
  'EMENDA-A-LOM-205' = 'EMENDA À LOM',
  'LEIS-MUNICIPAIS-3' = 'LEIS MUNICIPAIS',
  'LEI-COMPLEMENTAR-202' = 'LEI COMPLEMENTAR',
  'LEI-ORDINARIA-201' = 'LEI ORDINÁRIA',
  'MOCAO-43' = 'MOÇÃO',
  'RESOLUCAO-LEGISLATIVA-204' = 'RESOLUÇÃO LEGISLATIVA',
  'PARECER-620' = 'PARECER',
}
